/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_samples_fd_DetectionBasedTracker */

#ifndef _Included_org_opencv_samples_fd_DetectionBasedTracker
#define _Included_org_opencv_samples_fd_DetectionBasedTracker

#include <opencv2/core/core.hpp>
#include <vector>

#ifdef __cplusplus
extern "C" {
#endif

using namespace std;
using namespace cv;


JNIEXPORT void JNICALL Java_com_cleenr_cleenr_ObjectDetector_findContours(JNIEnv *, jclass, jlong, jlong);

void findAllRects(cv::Mat * pImage, vector<vector<Rect> > & allRects);
void findRectsInRow(cv::Mat * pImage, vector<Rect> & rectsInRow, int row);

void combineRects(vector<vector<Rect> > & allRects, vector<Rect> & combinedRects);
void combineRows(vector<Rect> & lowerRow, vector<Rect> & upperRow, vector<Rect> & combinedRects);
#ifdef __cplusplus
}
#endif
#endif
