/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/core/core.hpp>
/* Header for class org_opencv_samples_fd_DetectionBasedTracker */

#ifndef _Included_org_opencv_samples_fd_DetectionBasedTracker
#define _Included_org_opencv_samples_fd_DetectionBasedTracker
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT void JNICALL Java_com_cleenr_cleenr_ObjectDetector_findContours(JNIEnv *, jclass, jlong, jlong);
void findAllRects(cv::Mat * pImage, std::vector<cv::Rect> & allRects);

#ifdef __cplusplus
}
#endif
#endif
